services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  workermanager:
    build:
      context: .
      dockerfile: src/main/java/org/example/Worker/Dockerfile
    environment:
      - NUM_WORKERS=5
      - WORKER_START_PORT=8082
    networks:
      - mynetwork
    depends_on:
      - db

  loadbalancer:
    build:
      context: .
      dockerfile: src/main/java/org/example/LoadBalancer/Dockerfile
    environment:
      - SCHED_ALGO=LC
      - NUM_WORKERS=5
      - LB_PORT=8081
      - WORKER_START_PORT=8082
    networks:
      - mynetwork
    depends_on:
      - workermanager

  client:
    build:
      context: .
      dockerfile: src/main/java/org/example/Client/Dockerfile
    environment:
      - NUM_CLIENTS=1
      - LB_PORT=8081
    networks:
      - mynetwork
    depends_on:
      - loadbalancer


networks:
  mynetwork: